# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
  - OpenZeppelin/openzeppelin-contracts@3.1.0
  - iearn-finance/yearn-vaults@0.3.5-2

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV2=OpenZeppelin/openzeppelin-contracts@2.5.1"
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
      - "@yearnvaults=iearn-finance/yearn-vaults@0.4.3"
      
reports:
  exclude_contracts:
    - SafeMath
